openapi: '3.1.0'
info:
  title: Article analyzer
  description: |-
    nothing verfy interesting

  version: '1.0'
servers:
  - url: localhost:8080
tags:
  - name: analyze
    description: article analyzer

paths:
  /analyze:
    post:
      tags:
        - analyze
      summary: run article analyzer
      requestBody:
        content: 
          application/json:
            schema:
              $ref: '#/components/schemas/Article'
      responses:
        
   
components:
  schemas:
    Article:
      type: object
      properties:
        text: 
          type: string
          examples: 
            - "President Trump had another shot at the elections after mugshot had been released."